### PR TITLE
add dependabot for github actions

### PR DESCRIPTION
**Pull request by m-fila**
BEGINRELEASENOTES
- Added dependabot configuration to get updates for github actions

ENDRELEASENOTES

Basic configuration for dependabot to periodicaly scan repo's github workflows and open PR for updating the actions. 
I think this might be useful as some of the repos run deprecated versions of actions  (https://github.com/key4hep/key4hep-spack/pull/639)

- Dependabot [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- Example PR https://github.com/key4hep/key4hep-julia-fwk/pull/15

There shouldn't be any conflict as only https://github.com/key4hep/key4hep-julia-fwk and https://github.com/key4hep/spack have already this file

### CODE REVIEW

**Comment by jmcarcell** [comment]
Should this be pushed to every repository though? The PRs on outdated dependencies on files that are overwritten are useless everywhere else but here. So in this repo it would make sense to run it. In addition, for example for the Key4hep builds in CI, there is an action here that is called from the workflow files, so if the action has outdated dependencies does the bot check it and then make a PR to the original repository? I would think that it doesn't.

**Comment by tmadlener** [comment]
Can we configure the dependabot to only monitor the workflows that are not centrally managed? Some repositories might have such workflows. I agree that there is no real need to monitor the common key4hep-build workflow which we push centrally in any case.

**Comment by m-fila** [comment]
You are right that would create a lot useless PRs for centrally managed actions

>  so if the action has outdated dependencies does the bot check it and then make a PR to the original repository? I would think that it doesn't.

dependabot will not follow actions to their origin and open PR for its own deps

> Can we configure the dependabot to only monitor the workflows that are not centrally managed?

Unfortunately currently this is not possible :confused:

I think we could instead put this in key4hep-actions to cover just the managed actions and workflows

**Comment by m-fila** [comment]
Closing this in favor of key4hep/key4hep-actions#8 for updating centrally managed workflows

**Pull request closed without merging**
